name: GrassSimulator
version: '1.0-SNAPSHOT'
main: com.example.grasssimulator.Main
api-version: '1.20'
softdepend: [ProtocolLib]
commands:
  hoeshop:
    description: Открывает магазин мотыг.
  mo:
    description: Выдает деньги игроку (только для админов).
  to:
    description: Выдает токены игроку (только для админов).
  upgradehoe:
    description: Открывает меню улучшения мотыги.
  cogdafeodal:
    description: Открывает меню ребитха.
  createlegendarychest:
    description: Создание лег сундука где стоит игрок
  balance:
    description: Показывает текущий баланс игрока.
  setbalance:
    description: Устанавливает игроку баланс
  settokens:
    description: Устанавливает игроку токены
  createpetchest: